name: deploy the python project
on: push
jobs: 
  build: 
    runs-on: self-hosted
    steps: 
      - name: get code
        uses: actions/checkout@v3
      - name: Install the docker packages
        run: | 
           sudo apt-get update -y
           sudo apt install docker.io -y
           sudo usermod -aG docker ubuntu
           sudo chmod 777 /var/run/docker.sock
           sudo systemctl restart docker
      - name: Build the dockerfile
        run: | 
          docker build -t python-app:v3 . 
      - name: containerized python apps
        run : | 
          docker run -itd --name python-app1 -p 80:80 python-app:v3
